name: main

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'

      - uses: actions/checkout@v2

      - name: Build
        run: go build ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Tools
        run: |
          go install github.com/dvob/sko@latest
          echo "$( go env GOPATH )/bin" >> $GITHUB_PATH

      - name: Docker Hub Release
        env:
          SKO_USER: dvob
          SKO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
            sko -tag "${GITHUB_REF##*/}" -tag latest dvob/http-server .

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
